myfinance-web-dotnet/Models/ErrorViewModel.cs
namespace myfinance_web_dotnet.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

myfinance-web-dotnet/Models/PlanoContaModel.cs
namespace myfinance_web_dotnet.Models;

public class PlanoContaModel
{
    public int? Id { get; set; }
    public string Descricao { get; set; }
    public string Tipo { get; set; }
}

myfinance-web-dotnet/Models/TransacaoModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace myfinance_web_dotnet.Models;
public class TransacaoModel
{
    public int? Id { get; set; }
    public string Historico { get; set; }
    public DateTime Data { get; set; }
    public decimal Valor { get; set; }
    public int Id_Plano_Conta { get; set; }
    public string? Tipo { get; set; }
    public IEnumerable<SelectListItem>? ListaPlanoContas { get; set; }
}

myfinance-web-dotnet/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using myfinance_web_dotnet.Models;

namespace myfinance_web_dotnet.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

myfinance-web-dotnet/Controllers/PlanoContaController.cs
using Microsoft.AspNetCore.Mvc;
using myfinance_web_dotnet.Models;
using myfinance_web_dotnet_domain.Entities;
using myfinance_web_dotnet_service.Interfaces;

namespace myfinance_web_dotnet.Controllers
{
    [Route("[controller]")]
    public class PlanoContaController : Controller
    {
        private readonly ILogger<PlanoContaController> _logger;
        private readonly IPlanoContaService _planoContaService;

        public PlanoContaController(ILogger<PlanoContaController> logger, IPlanoContaService planoContaService)
        {
            _logger = logger;
            _planoContaService = planoContaService;
        }

        [HttpGet]
        [Route("Index")]
        public IActionResult Index()
        {
            var listaPlanoContas = _planoContaService.ListarRegistros();
            List<PlanoContaModel> listaPlanoContaModel = new List<PlanoContaModel>();

            foreach (var item in listaPlanoContas)
            {
                var planoContaModel = new PlanoContaModel() {
                    Id = item.Id,
                    Descricao = item.Descricao,
                    Tipo = item.Tipo
                };

                listaPlanoContaModel.Add(planoContaModel);
            }

            ViewBag.ListaPlanoConta = listaPlanoContaModel;
            
            return View();
        }

        [HttpGet]
        [Route("Cadastrar")]
        [Route("Cadastrar/{Id}")]
        public IActionResult Cadastrar(int? id)
        {
            if (id != null)
            {
                var planoConta = _planoContaService.RetornarRegistro((int)id);
                var planoContaModel = new PlanoContaModel() {
                    Id = planoConta.Id,
                    Descricao = planoConta.Descricao,
                    Tipo = planoConta.Tipo
                };

                return View(planoContaModel);
            }
            return View();
        }

        [HttpPost]
        [Route("Cadastrar")]
        [Route("Cadastrar/{Id}")]
        public IActionResult Cadastrar(PlanoContaModel model)
        {
            var planoConta = new PlanoConta()
            {
                Id = model.Id,
                Descricao = model.Descricao,
                Tipo = model.Tipo
            };
            
            _planoContaService.Cadastrar(planoConta);

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("Excluir/{Id}")]
        public IActionResult Excluir(int? Id)    
        {
            _planoContaService.Excluir((int)Id);
            return RedirectToAction("Index");
        }
        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

myfinance-web-dotnet/Controllers/TransacaoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using myfinance_web_dotnet.Models;
using myfinance_web_dotnet_domain.Entities;
using myfinance_web_dotnet_service.Interfaces;

namespace myfinance_web_dotnet.Controllers
{
    [Route("[controller]")]
    public class TransacaoController : Controller
    {
        private readonly ILogger<TransacaoController> _logger;
        private readonly ITransacaoService _transacaoService;
        private readonly IPlanoContaService _planoContaService;

        public TransacaoController(ILogger<TransacaoController> logger, ITransacaoService transacaoService, IPlanoContaService planoContaService)
        {
            _logger = logger;
            _transacaoService = transacaoService;
            _planoContaService = planoContaService;
        }

        [HttpGet]
        [Route("Index")]
        public IActionResult Index()
        {
            var listaTransacoes = _transacaoService.ListarRegistros();
            List<TransacaoModel> listaTransacaoModel = new List<TransacaoModel>();

            foreach (var item in listaTransacoes)
            {
                var transacaoModel = new TransacaoModel() {
                    Id = item.Id,
                    Historico = item.Historico,
                    Data = item.Data,
                    Valor = item.Valor,
                    Tipo = item.PlanoConta.Tipo,
                    Id_Plano_Conta = item.Id_Plano_Conta
                };

                listaTransacaoModel.Add(transacaoModel);
            }

            ViewBag.ListaTransacao = listaTransacaoModel;
            
            return View();
        }

        [HttpGet]
        [Route("Cadastrar")]
        [Route("Cadastrar/{Id}")]
        public IActionResult Cadastrar(int? id)
        {
            var ListaPlanoContas = new SelectList(_planoContaService.ListarRegistros(), "Id", "Descricao");
            var itemTransacao = new TransacaoModel() {
                Data = DateTime.Now,
                ListaPlanoContas = ListaPlanoContas
            };

            if (id != null)
            {
                var transacao = _transacaoService.RetornarRegistro((int)id);
                
                itemTransacao.Id = transacao.Id;
                itemTransacao.Historico = transacao.Historico;
                itemTransacao.Valor = transacao.Valor;
                itemTransacao.Data = transacao.Data;
                itemTransacao.Id_Plano_Conta = transacao.Id_Plano_Conta;

            }
            return View(itemTransacao);
        }

        [HttpPost]
        [Route("Cadastrar")]
        [Route("Cadastrar/{Id}")]
        public IActionResult Cadastrar(TransacaoModel model)
        {
            var transacao = new Transacao()
            {
                Id = model.Id,
                Historico = model.Historico,
                Data = model.Data,
                Valor = model.Valor,
                Id_Plano_Conta = model.Id_Plano_Conta
            };
            
            _transacaoService.Cadastrar(transacao);

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("Excluir/{Id}")]
        public IActionResult Excluir(int? Id)    
        {
            _transacaoService.Excluir((int)Id);
            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

myfinance-web-dotnet/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

myfinance-web-dotnet/Views/PlanoConta/Index.cshtml
<h1>Plano de Contas</h1>

<button type="button" class="btn btn-block btn-primary" onclick="Novo()">Criar item de Plano de Conta</button>
<br><br>
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Descrição</th>
        <th>Tipo</th>
        <th>#</th>
        <th>#</th>
    </tr>

    @{
        foreach (var item in (List<PlanoContaModel>)ViewBag.ListaPlanoConta)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Descricao</td>
                <td>@item.Tipo</td>
                <td><button type="button" class="btn btn-block btn-outline-warning" onclick="Atualizar(@item.Id.ToString())">Editar</button></td>
                <td><button type="button" class="btn btn-block btn-outline-danger"onclick="Excluir(@item.Id.ToString())">Excluir</button></td>
            </tr>
        }
    }
</table>

<script>
    function Novo()
    {
        window.location.href = "../PlanoConta/Cadastrar";
    }

    function Atualizar(id)
    {
        window.location.href = "../PlanoConta/Cadastrar/" + id;
    }

    function Excluir(id)
    {
        window.location.href = "../PlanoConta/Excluir/" + id;
    }
</script>

myfinance-web-dotnet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - myfinance_web_dotnet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/myfinance_web_dotnet.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">myfinance_web_dotnet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PlanoConta" asp-action="Index">Plano de Contas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transacao" asp-action="Index">Transações</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - myfinance_web_dotnet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

myfinance-web-dotnet/Views/Transacao/Cadastrar.cshtml
@model myfinance_web_dotnet.Models.TransacaoModel

@{
    ViewData["Title"] = "Registrar transação financeira";
}

<h1>@ViewData["Title"]</h1>

<div>
    <form asp-action="Cadastrar" asp-controller="Transacao" method="post">
        <input type="hidden" asp-for="Id"/><br>

        <div class="form-group">
            <label>Data:</label><br>
            <input type="date" class="form-control" asp-for="Data"/><br>
        </div>

        <div class="form-group">
            <label>Valor:</label><br>
            <input type="text" class="form-control" asp-for="Valor" step="0.01"/><br>
        </div>

        <div class="form-group">
            <label>Plano de Conta:</label>
            @Html.DropDownList("Id_Plano_Conta", Model.ListaPlanoContas, new { @class = "form-select"})
        </div>

        <div class="form-group">
            <label>Histórico:</label><br>
            <input type="text" class="form-control" asp-for="Historico"/><br>
        </div>

        <br><br>

        <div class="mb-3">
            <button type="submit" class="btn btn-primary btn-lg">Salvar</button>
            <button type="button" class="btn btn-secondary btn-lg">Cancelar</button>
        </div>
    </form>
</div>

<script>
    function Voltar() {
        window.location.href = "/Transacao"
    }
</script>

myfinance-web-dotnet/Views/Transacao/Index.cshtml
@{
    ViewData["Title"] = "Transações Financeiras";
}

<h1>@ViewData["Title"]</h1>

<button type="button" class="btn btn-block btn-primary" onclick="Novo()">Registrar Transação</button>
<br><br>
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Histórico</th>
        <th>Tipo</th>
        <th>Valor</th>
        <th>Data</th>
        <th>#</th>
        <th>#</th>
    </tr>

    @{
        foreach (var item in (List<TransacaoModel>)ViewBag.ListaTransacao)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Historico</td>
                <td>@item.Tipo</td>
                <td>@item.Valor</td>
                <td>@item.Data</td>
                <td><button type="button" class="btn btn-block btn-outline-warning" onclick="Atualizar(@item.Id.ToString())">Editar</button></td>
                <td><button type="button" class="btn btn-block btn-outline-danger"onclick="Excluir(@item.Id.ToString())">Excluir</button></td>
            </tr>
        }
    }
</table>

<script>
    function Novo()
    {
        window.location.href = "../Transacao/Cadastrar";
    }

    function Atualizar(id)
    {
        window.location.href = "../Transacao/Cadastrar/" + id;
    }

    function Excluir(id)
    {
        window.location.href = "../Transacao/Excluir/" + id;
    }
</script>